// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOBTpVtPGUEsKGNSs-xSi-ztvnkAVby-Y',
    appId: '1:357499313110:web:f3109150a62d30d16e6277',
    messagingSenderId: '357499313110',
    projectId: 'pojikhalyrazomus2',
    authDomain: 'pojikhalyrazomus2.firebaseapp.com',
    storageBucket: 'pojikhalyrazomus2.firebasestorage.app',
    measurementId: 'G-JKSEY7CYEZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAr7c0YBHIVWgrc408yGvmJ1F8OcuDBvvg',
    appId: '1:357499313110:android:741c345e7208143a6e6277',
    messagingSenderId: '357499313110',
    projectId: 'pojikhalyrazomus2',
    storageBucket: 'pojikhalyrazomus2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNphzIECDqZAaB43QC93nD1zSaUtckLa4',
    appId: '1:357499313110:ios:83e290e71f45bb026e6277',
    messagingSenderId: '357499313110',
    projectId: 'pojikhalyrazomus2',
    storageBucket: 'pojikhalyrazomus2.firebasestorage.app',
    iosBundleId: 'com.example.app1',
  );

}